# fly.toml app configuration file generated for nameless-haze-1185 on 2023-10-27T19:37:12+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nameless-haze-1185"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
